// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace OrderModule.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("E-commerce Order Pricing Promotions")]
    [NUnit.Framework.CategoryAttribute("order_pricing")]
    public partial class E_CommerceOrderPricingPromotionsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "order_pricing"};
        
#line 1 "OrderPricing.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "E-commerce Order Pricing Promotions", "  As a shopper\r\n  I want the system to calculate my order total with applicable p" +
                    "romotions\r\n  So that I can understand how much to pay and what items I will rece" +
                    "ive", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Single product without promotions")]
        public void SingleProductWithoutPromotions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Single product without promotions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given("no promotions are applied", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "productName",
                            "quantity",
                            "unitPrice"});
                table9.AddRow(new string[] {
                            "T-shirt",
                            "1",
                            "500"});
#line 9
    testRunner.When("a customer places an order with:", ((string)(null)), table9, "When ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "totalAmount"});
                table10.AddRow(new string[] {
                            "500"});
#line 12
    testRunner.Then("the order summary should be:", ((string)(null)), table10, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "productName",
                            "quantity"});
                table11.AddRow(new string[] {
                            "T-shirt",
                            "1"});
#line 15
    testRunner.And("the customer should receive:", ((string)(null)), table11, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Threshold discount applies when subtotal reaches 1000")]
        public void ThresholdDiscountAppliesWhenSubtotalReaches1000()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Threshold discount applies when subtotal reaches 1000", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "threshold",
                            "discount"});
                table12.AddRow(new string[] {
                            "1000",
                            "100"});
#line 20
    testRunner.Given("the threshold discount promotion is configured:", ((string)(null)), table12, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "productName",
                            "quantity",
                            "unitPrice"});
                table13.AddRow(new string[] {
                            "T-shirt",
                            "2",
                            "500"});
                table13.AddRow(new string[] {
                            "褲子",
                            "1",
                            "600"});
#line 23
    testRunner.When("a customer places an order with:", ((string)(null)), table13, "When ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "originalAmount",
                            "discount",
                            "totalAmount"});
                table14.AddRow(new string[] {
                            "1600",
                            "100",
                            "1500"});
#line 27
    testRunner.Then("the order summary should be:", ((string)(null)), table14, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "productName",
                            "quantity"});
                table15.AddRow(new string[] {
                            "T-shirt",
                            "2"});
                table15.AddRow(new string[] {
                            "褲子",
                            "1"});
#line 30
    testRunner.And("the customer should receive:", ((string)(null)), table15, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Buy-one-get-one for cosmetics - multiple products")]
        public void Buy_One_Get_OneForCosmetics_MultipleProducts()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buy-one-get-one for cosmetics - multiple products", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 36
    testRunner.Given("the buy one get one promotion for cosmetics is active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "productName",
                            "category",
                            "quantity",
                            "unitPrice"});
                table16.AddRow(new string[] {
                            "口紅",
                            "cosmetics",
                            "1",
                            "300"});
                table16.AddRow(new string[] {
                            "粉底液",
                            "cosmetics",
                            "1",
                            "400"});
#line 37
    testRunner.When("a customer places an order with:", ((string)(null)), table16, "When ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "totalAmount"});
                table17.AddRow(new string[] {
                            "700"});
#line 41
    testRunner.Then("the order summary should be:", ((string)(null)), table17, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "productName",
                            "quantity"});
                table18.AddRow(new string[] {
                            "口紅",
                            "2"});
                table18.AddRow(new string[] {
                            "粉底液",
                            "2"});
#line 44
    testRunner.And("the customer should receive:", ((string)(null)), table18, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Buy-one-get-one for cosmetics - same product twice")]
        public void Buy_One_Get_OneForCosmetics_SameProductTwice()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buy-one-get-one for cosmetics - same product twice", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 50
    testRunner.Given("the buy one get one promotion for cosmetics is active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "productName",
                            "category",
                            "quantity",
                            "unitPrice"});
                table19.AddRow(new string[] {
                            "口紅",
                            "cosmetics",
                            "2",
                            "300"});
#line 51
    testRunner.When("a customer places an order with:", ((string)(null)), table19, "When ");
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "totalAmount"});
                table20.AddRow(new string[] {
                            "600"});
#line 54
    testRunner.Then("the order summary should be:", ((string)(null)), table20, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "productName",
                            "quantity"});
                table21.AddRow(new string[] {
                            "口紅",
                            "3"});
#line 57
    testRunner.And("the customer should receive:", ((string)(null)), table21, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Buy-one-get-one for cosmetics - mixed categories")]
        public void Buy_One_Get_OneForCosmetics_MixedCategories()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buy-one-get-one for cosmetics - mixed categories", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 62
    testRunner.Given("the buy one get one promotion for cosmetics is active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "productName",
                            "category",
                            "quantity",
                            "unitPrice"});
                table22.AddRow(new string[] {
                            "襪子",
                            "apparel",
                            "1",
                            "100"});
                table22.AddRow(new string[] {
                            "口紅",
                            "cosmetics",
                            "1",
                            "300"});
#line 63
    testRunner.When("a customer places an order with:", ((string)(null)), table22, "When ");
#line hidden
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "totalAmount"});
                table23.AddRow(new string[] {
                            "400"});
#line 67
    testRunner.Then("the order summary should be:", ((string)(null)), table23, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "productName",
                            "quantity"});
                table24.AddRow(new string[] {
                            "襪子",
                            "1"});
                table24.AddRow(new string[] {
                            "口紅",
                            "2"});
#line 70
    testRunner.And("the customer should receive:", ((string)(null)), table24, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Multiple promotions stacked")]
        public void MultiplePromotionsStacked()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Multiple promotions stacked", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 75
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "threshold",
                            "discount"});
                table25.AddRow(new string[] {
                            "1000",
                            "100"});
#line 76
    testRunner.Given("the threshold discount promotion is configured:", ((string)(null)), table25, "Given ");
#line hidden
#line 79
    testRunner.And("the buy one get one promotion for cosmetics is active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "productName",
                            "category",
                            "quantity",
                            "unitPrice"});
                table26.AddRow(new string[] {
                            "T-shirt",
                            "apparel",
                            "3",
                            "500"});
                table26.AddRow(new string[] {
                            "口紅",
                            "cosmetics",
                            "1",
                            "300"});
#line 80
    testRunner.When("a customer places an order with:", ((string)(null)), table26, "When ");
#line hidden
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "originalAmount",
                            "discount",
                            "totalAmount"});
                table27.AddRow(new string[] {
                            "1800",
                            "100",
                            "1700"});
#line 84
    testRunner.Then("the order summary should be:", ((string)(null)), table27, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "productName",
                            "quantity"});
                table28.AddRow(new string[] {
                            "T-shirt",
                            "3"});
                table28.AddRow(new string[] {
                            "口紅",
                            "2"});
#line 87
    testRunner.And("the customer should receive:", ((string)(null)), table28, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
